name: veyo
description: "Smart urban mobility app for Africa's transport system"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core Flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.7
  intl: ^0.20.2

  # Mapping
  google_maps_flutter: ^2.6.0

  # Firebase
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  firebase_storage: ^12.4.6

  # Social Auth
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.0.4
  sign_in_with_apple: ^7.0.1

  # Icons
  font_awesome_flutter: ^10.7.0

  # State Management
  provider: ^6.1.2
  flutter_riverpod: ^2.5.1

  # Utilities
  geolocator: ^10.1.0
  http: ^0.13.3
  shared_preferences: ^2.2.2
  flutter_dotenv: ^5.1.0

  # Image handling
  cached_network_image: ^3.3.0
  flutter_cache_manager: ^3.3.1

  # Google Places Autocomplete
  google_place: ^0.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mockito: ^5.4.4
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    # Environment
    - .env
    
    # Icons
    - assets/images/icons/google.svg
    - assets/images/icons/mpesa.png
    
    # Category Images
    - assets/images/public_transport.jpg
    - assets/images/carpool.jpg
    - assets/images/delivery.jpg
    - assets/images/geolocation.jpg
    - assets/images/electric_car.jpg
    - assets/images/women_only.jpg
    - assets/images/green_points.jpg
    - assets/images/tree_planting.jpg
    # Trip Option Images
    - assets/images/boda_option.jpg
    - assets/images/bus_option.jpg
    - assets/images/car_option.jpg
    - assets/images/matatu_option.jpg

flutter_icons:
  android: true
  ios: false
  image_path: "assets/images/app_logo.png"

